server:
  port: 9492
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/isankha007/config-server
          clone-on-start: true